#!/bin/sh

set -e

apt-get purge dnsmasq hostapd
apt-get install -y dnsmasq
cd /tmp
wget http://old-releases.ubuntu.com/ubuntu/pool/universe/w/wpa/hostapd_1.0-3ubuntu2.1_amd64.deb
dpkg -i hostapd_1.0-3ubuntu2.1_amd64.deb

#DEBHELPER#

exit 0

# vim: ts=2 sw=2